const seedData = [
  {
    name: "Blue Bottle",
    category: "coffee",
    neighborhood: "Santana Row",
    rating: -1,
    img: "https://i.imgur.com/CHssUFE.jpg",
    attributes: ["Outdoor Seating", "Bathrooms Available", "Water Available"],
    links: {
      instagram: "bluebottle",
      map: "368 Santana Row Suite 1020, San Jose, CA 95128",
    },
    loc: {
      type: "Point",
      coordinates: [-121.9478553, 37.3202302],
    },
  },
  {
    name: "Papermoon Cafe",
    category: "coffee",
    neighborhood: "West SanJose",
    img: "https://i.imgur.com/8sFGnAM.jpg",
    attributes: [
      "Outdoor Seating",
      "Locally Owned",
      "Bathrooms Available",
      "Water Available",
    ],
    links: {
      instagram: "papermooncoffeeco",
      map: "5237 Stevens Creek Blvd, Santa Clara, CA 95051",
    },
    loc: {
      type: "Point",
      coordinates: [-121.9944611, 37.3239944],
    },
  },
  {
    name: "Voyager Craft Coffee",
    category: "coffee",
    neighborhood: "Downtown Santa Clara",
    rating: -1,
    img: "https://i.imgur.com/pJNh1rf.jpg",
    attributes: ["Locally Owned", "Bathrooms Available", "Water Available"],
    links: {
      instagram: "voyagercraftcoffee",
      map: "2221 The Alameda, Santa Clara, CA 95050",
    },
    loc: {
      type: "Point",
      coordinates: [-121.9944611, 37.3239944],
    },
  },
  {
    name: "Voyager Craft Coffee",
    category: "coffee",
    neighborhood: "West San Jose",
    rating: -1,
    img: "https://i.imgur.com/cjR1SM1.jpg",
    attributes: [
      "Locally Owned",
      "Bike Parking Available",
      "Bathrooms Available",
      "Water Available",
    ],
    links: {
      instagram: "voyagercraftcoffee",
      map: "3985 Stevens Creek Blvd, Santa Clara, CA 95051",
    },
    loc: {
      type: "Point",
      coordinates: [-121.972528, 37.32362],
    },
  },
  {
    name: "Sue's Gallery Cafe",
    category: "coffee",
    neighborhood: "Downtown Saratoga",
    rating: -1,
    img: "https://i.imgur.com/WhEaShP.jpg",
    links: {
      instagram: "suesgallerycafe",
      map: "14665 Big Basin Way, Saratoga, CA 95070",
    },
    attributes: [
      "Outdoor Seating",
      "Locally Owned",
      "Bike Parking Available",
      "Bathrooms Available",
      "Water Available",
    ],
    loc: { type: "Point", coordinates: [-122.0374028, 37.2558028] },
  },
  {
    name: "Manresa Bread",
    category: "coffee",
    neighborhood: "Downtown Campbell",
    rating: -1,
    img: "https://i.imgur.com/E68FRuK.jpg",
    links: {
      instagram: "manresabread",
      map: "195 E Campbell Ave, Campbell, CA 95008",
    },
    attributes: ["Locally Owned", "Bathrooms Available", "Water Available"],
    loc: { type: "Point", coordinates: [-121.9466851, 37.2872623] },
  },
  {
    name: "Manresa Bread",
    category: "coffee",
    neighborhood: "Downtown Los Gatos",
    rating: -1,
    img: "https://i.imgur.com/a5ChXlm.jpg",
    links: {
      instagram: "manresabread",
      map: "276 N Santa Cruz Ave, Los Gatos, CA 95030",
    },
    attributes: ["Locally Owned", "Bathrooms Available", "Water Available"],
    loc: { type: "Point", coordinates: [-121.9808364, 37.2273788] },
  },
  {
    name: "Orchard Valley Coffee",
    category: "coffee",
    neighborhood: "Downtown Campbell",
    rating: -1,
    img: "https://i.imgur.com/DwqYEtM.jpg",
    links: { map: "349 E Campbell Ave, Campbell, CA 95008" },
    attributes: [
      "Outdoor Seating",
      "Locally Owned",
      "Bike Parking Available",
      "Bathrooms Available",
      "Water Available",
    ],
    loc: { type: "Point", coordinates: [-121.9437394, 37.2871612] },
  },
  {
    name: "Loma Coffee Bar",
    category: "coffee",
    neighborhood: "Downtown Los Gatos",
    rating: -1,
    img: "https://i.imgur.com/8p0cdc9.jpg",
    links: {
      instagram: "lomabrew",
      map: "130 N Santa Cruz Ave, Los Gatos, CA 95030",
    },
    attributes: ["Locally Owned", "Bathrooms Available", "Water Available"],
    loc: { type: "Point", coordinates: [-121.9823489, 37.2251501] },
  },
  {
    name: "Philz Coffee",
    category: "coffee",
    neighborhood: "Campbell",
    rating: -1,
    img: "https://i.imgur.com/UHj7oAf.jpg",
    links: {
      instagram: "philzcampbell",
      map: "1976 S Bascom Ave, Campbell, CA 95008",
    },
    attributes: [
      "Outdoor Seating",
      "Bike Parking Available",
      "Bathrooms Available",
      "Water Available",
    ],
    loc: { type: "Point", coordinates: [-121.931356, 37.2875295] },
  },
  {
    name: "Barefoot Coffee",
    category: "coffee",
    neighborhood: "Campbell",
    rating: -1,
    img: "https://i.imgur.com/oJRFrzz.jpg",
    links: {
      instagram: "barefootcoffeecampbell",
      map: "1819 S Bascom Ave, Campbell, CA 95008",
    },
    attributes: ["Locally Owned", "Bathrooms Available", "Water Available"],

    loc: { type: "Point", coordinates: [-121.9320264, 37.3303865] },
  },
];

module.exports = seedData;
