const seedData = [
  {
    name: "Blue Bottle",
    category: "coffee",
    neighborhood: "Santana Row",
    rating: -1,
    attributes: [],
    links: {},
    loc: {
      type: "Point",
      coordinates: [-121.9478553, 37.3202302],
    },
  },
  {
    name: "Papermoon Cafe",
    category: "coffee",
    neighborhood: "West SanJose",
    rating: -1,
    attributes: {},
    links: { instagram: "papermooncoffeeco" },
    loc: {
      type: "Point",
      coordinates: [-121.9944611, 37.3239944],
    },
  },
  {
    name: "Voyager Craft Coffee",
    category: "coffee",
    neighborhood: "Downtown Santa Clara",
    rating: -1,
    attributes: {},
    links: { instagram: "voyagercraftcoffee" },
    loc: {
      type: "Point",
      coordinates: [-121.9944611, 37.3239944],
    },
  },
  {
    name: "Voyager Craft Coffee",
    category: "coffee",
    neighborhood: "San Pedro SQ Downtown San Jose",
    rating: -1,
    attributes: {},
    links: { instagram: "voyagercraftcoffee" },
    loc: {
      type: "Point",
      coordinates: [-121.8943208, 37.3365212],
    },
  },
  {
    name: "Voyager Craft Coffee",
    category: "coffee",
    neighborhood: "West San Jose",
    rating: -1,
    attributes: {},
    links: { instagram: "voyagercraftcoffee" },
    loc: {
      type: "Point",
      coordinates: [-121.972528, 37.32362],
    },
  },
  {
    name: "Sue's Gallery Cafe",
    category: "coffee",
    neighborhood: "Downtown Saratoga",
    rating: -1,
    attributes: [{ instagram: "suesgallerycafe" }],
    loc: { type: "Point", coordinates: [-122.0374028, 37.2558028] },
  },
  {
    name: "Big Mug Coffee Roasters",
    category: "coffee",
    neighborhood: "El Camino",
    rating: -1,
    attributes: [{ instagram: "bigmugcoffee" }],
    loc: { type: "Point", coordinates: [-121.980882, 37.3515167] },
  },
  {
    name: "Academic Coffee",
    category: "coffee",
    neighborhood: "Downtown SanJose",
    rating: -1,
    attributes: [{ instagram: "academiccoffeesj" }],
    loc: { type: "Point", coordinates: [-121.8840982, 37.3291328] },
  },
  {
    name: "Voltaire Coffee Roasters",
    category: "coffee",
    neighborhood: "Downtown SanJose",
    rating: -1,
    attributes: [{ instagram: "voltairecoffeeroasters" }],
    loc: { type: "Point", coordinates: [-121.8868481, 37.3298891] },
  },
  {
    name: "Evergreen Coffee Roasters",
    category: "coffee",
    neighborhood: "Evergreen",
    rating: -1,
    attributes: [{ instagram: "evergreencoffeeco" }],
    loc: { type: "Point", coordinates: [-121.7736079, 37.3142137] },
  },
  {
    name: "Roy’s Station Coffee & Teas",
    category: "coffee",
    neighborhood: "JapanTown",
    rating: -1,
    attributes: [{ instagram: "roysstation" }],
    loc: { type: "Point", coordinates: [-121.894717, 37.3490192] },
  },
  {
    name: "Chromatic Coffee",
    category: "coffee",
    neighborhood: "Midtown",
    rating: -1,
    attributes: [{ instagram: "chromaticcoffee" }],
    loc: { type: "Point", coordinates: [-121.894717, 37.3490192] },
  },
  {
    name: "Crema Coffee Roasting Co.",
    category: "coffee",
    neighborhood: "the Alameda",
    rating: -1,
    attributes: [],
    loc: { type: "Point", coordinates: [-121.9117863, 37.3317526] },
  },
  {
    name: "Manresa Bread",
    category: "coffee",
    neighborhood: "Downtown Campbell",
    rating: -1,
    attributes: [],
    loc: { type: "Point", coordinates: [-121.9466851, 37.2872623] },
  },
  {
    name: "Manresa Bread",
    category: "coffee",
    neighborhood: "Downtown Los Gatos",
    rating: -1,
    attributes: [],
    loc: { type: "Point", coordinates: [-121.9808364, 37.2273788] },
  },
  {
    name: "Red Rock",
    category: "coffee",
    neighborhood: "Downtown Mountain View",
    rating: -1,
    attributes: [],
    loc: { type: "Point", coordinates: [-122.0787562, 37.3936221] },
  },
  {
    name: "Pastelaria Adega",
    category: "coffee",
    neighborhood: "Downtown San Jose",
    rating: -1,
    attributes: [{ instagram: "pastelariaadega" }],
    loc: { type: "Point", coordinates: [-121.8898133, 37.336259] },
  },
  {
    name: "Orchard Valley Coffee",
    category: "coffee",
    neighborhood: "Downtown Campbell",
    rating: -1,
    attributes: [],
    loc: { type: "Point", coordinates: [-121.9437394, 37.2871612] },
  },
  {
    name: "Cafe Dio",
    category: "coffee",
    neighborhood: "Downtown Los Gatos",
    rating: -1,
    attributes: [],
    loc: { type: "Point", coordinates: [-121.97738, 37.221337] },
  },
  {
    name: "Loma Coffee Bar",
    category: "coffee",
    neighborhood: "Downtown Los Gatos",
    rating: -1,
    attributes: [{ instagram: "philzcatz" }],
    loc: { type: "Point", coordinates: [-121.9823489, 37.2251501] },
  },
  {
    name: "Coffee & More",
    category: "coffee",
    neighborhood: "Downtown Sunnyvale",
    rating: -1,
    attributes: [],
    loc: { type: "Point", coordinates: [-122.0296601, 37.3773576] },
  },
  {
    name: "Café Lattea",
    category: "coffee",
    neighborhood: "Main Street Cupertino",
    rating: -1,
    attributes: [{ instagram: "cafelatteacupertino" }],
    loc: { type: "Point", coordinates: [-122.0123435, 37.3231977] },
  },
  {
    name: "Philz Coffee",
    category: "coffee",
    neighborhood: "Main Street Cupertino",
    rating: -1,
    attributes: [{ instagram: "philzmainst" }],
    loc: { type: "Point", coordinates: [-122.0104896, 37.3245007] },
  },
  {
    name: "Philz Coffee",
    category: "coffee",
    neighborhood: "Campbell",
    rating: -1,
    attributes: [{ instagram: "philzcampbell" }],
    loc: { type: "Point", coordinates: [-121.931356, 37.2875295] },
  },
  {
    name: "Philz Coffee",
    category: "coffee",
    neighborhood: "Downtown San Jose",
    rating: -1,
    attributes: [{ instagram: "philzsj" }],
    loc: { type: "Point", coordinates: [-121.8851394, 37.3335189] },
  },
  {
    name: "Philz Coffee",
    category: "coffee",
    neighborhood: "Downtown Sunnyvale",
    rating: -1,
    attributes: [{ instagram: "cafelatteacupertino" }],
    loc: { type: "Point", coordinates: [-122.0313897, 37.3773354] },
  },
  {
    name: "Vero's Coffee Bar",
    category: "coffee",
    neighborhood: "SoFA Downtown San Jose",
    rating: -1,
    attributes: [{ instagram: "veroscoffeebar" }],
    loc: { type: "Point", coordinates: [-121.8864387, 37.3303865] },
  },
  {
    name: "Barefoot Coffee",
    category: "coffee",
    neighborhood: "Campbell",
    rating: -1,
    attributes: [{ instagram: "barefootcoffeecampbell" }],
    loc: { type: "Point", coordinates: [-121.9320264, 37.3303865] },
  },
  {
    name: "K Cafe Patisserie & Tea House",
    category: "coffee",
    neighborhood: "West San Jose",
    rating: -1,
    attributes: [{ instagram: "kcafeteahouse" }],
    loc: { type: "Point", coordinates: [-121.9321561, 37.3095448] },
  },
  {
    name: "Bitter+Sweet",
    category: "coffee",
    neighborhood: "Cupertino",
    rating: -1,
    attributes: [{ instagram: "kcafeteahouse" }],
    loc: { type: "Point", coordinates: [-122.031522, 37.3181711] },
  },
  {
    name: "1 Oz Coffee",
    category: "coffee",
    neighborhood: "Downtown Mountain View",
    rating: -1,
    attributes: [{ instagram: "1oz_coffee" }],
    loc: { type: "Point", coordinates: [-122.0829527, 37.3878654] },
  },
  {
    name: "1 Oz Coffee",
    category: "coffee",
    neighborhood: "Santa Clara",
    rating: -1,
    attributes: [{ instagram: "1oz_coffee" }],
    loc: { type: "Point", coordinates: [-121.982848, 37.4046071] },
  },
  {
    name: "Cafe Big Mug",
    category: "coffee",
    neighborhood: "West San Jose",
    rating: -1,
    attributes: [{ instagram: "bigmugcoffee" }],
    loc: { type: "Point", coordinates: [-121.968462, 37.3239691] },
  },
  {
    name: "Cafe Benne",
    category: "coffee",
    neighborhood: "North San Jose",
    rating: -1,
    attributes: [{ instagram: "caffebene.sanjose" }],
    loc: { type: "Point", coordinates: [-121.937611, 37.41277] },
  },
  {
    name: "Hannah Coffee & Sweets",
    category: "coffee",
    neighborhood: "the Alameda San Jose",
    rating: -1,
    attributes: [{ instagram: "hannahcoffeeteasweets" }],
    loc: { type: "Point", coordinates: [-121.905534, 37.331574] },
  },
  {
    name: "Great Bear Coffee",
    category: "coffee",
    neighborhood: "Downtown Los Gatos",
    rating: -1,
    attributes: [{ instagram: "hannahcoffeeteasweets" }],
    loc: { type: "Point", coordinates: [-121.9837, 37.2232028] },
  },
  {
    name: "Los Gatos Coffee Roasting Company",
    category: "coffee",
    neighborhood: "Downtown Los Gatos",
    rating: -1,
    attributes: [{ instagram: "hannahcoffeeteasweets" }],
    loc: { type: "Point", coordinates: [-121.983, 37.222] },
  },
  {
    name: "Bel Bacio Cafe",
    category: "coffee",
    neighborhood: "Little Italy",
    rating: -1,
    attributes: [{ instagram: "belbacioitaliancafe" }],
    loc: { type: "Point", coordinates: [-121.8985261, 37.3358125] },
  },
  {
    name: "Dana Street Roasting Company",
    category: "coffee",
    neighborhood: "Downtown Mountain View",
    rating: -1,
    attributes: [{ instagram: "danastreetroasting" }],
    loc: { type: "Point", coordinates: [-122.0790417, 37.3924139] },
  },
  {
    name: "Maison Alyzée",
    category: "coffee",
    neighborhood: "Downtown Mountain View",
    rating: -1,
    attributes: [{ instagram: "maisonalyzee" }],
    loc: { type: "Point", coordinates: [-122.0793244e, 37.3937182] },
  },
];
