import pic1 from "./sjsu.png";

export default [
  {
    id: 1,
    type: "coffee",
    name: "Voyager Craft Coffee",
    neighborhood: "San Pedro Square",
    city: "San Jose",
    time: "20 min",
    image: pic1,
  },
  {
    id: 2,
    type: "coffee",
    name: "Big Mug Coffee",
    neighborhood: "El Camino Business District",
    city: "Santa Clara",
    time: "15 min",
    image: pic1,
  },

  {
    id: 3,
    type: "view",
    name: "Vasona Park",
    neighborhood: "Los Gatos Creek Trail",
    city: "Los Gatos",
    image: pic1,
  },
  {
    id: 4,
    type: "coffee",
    name: "Blue Bottle Coffee",
    city: "San Jose",
    time: "15 min",
    image: pic1,
  },
  {
    id: 5,
    name: "Tower Hall",
    neighborhood: "San Jose State",
    city: "San Jose",
    time: "5 min",
    image: pic1,
  },
  {
    type: "view",
    name: "Baylands Park",
    neighborhood: "Alviso",
    city: "San Jose",
    time: "20 min",
    image: pic1,
  },
  {
    id: 7,
    type: "view",
    name: "Baylands Park",
    neighborhood: "Alviso",
    city: "San Jose",
    time: "20 min",
    image: pic1,
  },
  {
    id: 8,
    type: "landmark",
    name: "Campbell Water Tower",
    neighborhood: "Downtown Campbell",
    city: "Campbell",
    time: "5 min",
    image: pic1,
  },
  {
    id: 9,
    type: "landmark",
    name: "Don Burnette Bridge",
    neighborhood: "De Anza College",
    city: "Cupertino",
    time: "18 min",
    image: pic1,
  },
];
