// import pic1 from "./sjsu.png";

export default [
  {
    name: "Blue Bottle",
    category: "coffee",
    neighborhood: "Santana Row",
    rating: 4.9,
    distanceMiles: 5,
  },
  {
    name: "Papermoon Cafe",
    category: "coffee",
    neighborhood: "Santana Row",
    rating: 3.5,
    distanceMiles: 6,
  },
  {
    name: "Voyager Craft Coffee",
    category: "coffee",
    neighborhood: "Downtown Santa Clara",
    rating: 4.5,
    distanceMiles: 7,
  },
  {
    name: "Sue's Gallery Cafe",
    category: "coffee",
    neighborhood: "Downtown Saratoga",
    rating: 5,
    distanceMiles: 4,
  },
  {
    name: "Vasona Lake",
    category: "view",
    neighborhood: "Los Gatos Creek",
    rating: 4.5,
    distanceMiles: 3,
  },

  {
    name: "Communication Hills",
    category: "view",
    neighborhood: "South San Jose",
    rating: 5,
    distanceMiles: 8,
  },
  {
    name: "Baylands Park",
    category: "view",
    neighborhood: "North San Jose",
    rating: 4.9,
    distanceMiles: 5,
  },
  {
    name: "Campbell Perc Ponds",
    category: "view",
    neighborhood: "Los Gatos Creek",
    rating: 4.5,
    distanceMiles: 3,
  },

  {
    name: "SJSU Tower Hall",
    category: "landmark",
    neighborhood: "San Jose State University",
    rating: 4.9,
    distanceMiles: 5,
  },
  {
    name: "Mission Santa Clara",
    category: "landmark",
    neighborhood: "Santa Clara University",
    rating: 4,
    distanceMiles: 6,
  },
  {
    name: "Farm Milk Dairy",
    category: "landmark",
    neighborhood: "HazelWood",
    rating: 5,
    distanceMiles: 0.1,
  },
  {
    name: "Campbell Water Tower",
    category: "landmark",
    neighborhood: "Downtown Campbell",
    rating: 4.9,
    distanceMiles: 5,
  },
];

// import pic1 from "./sjsu.png";

// export default [
//   {
//     id: 1,
//     type: "coffee",
//     name: "Voyager Craft Coffee",
//     neighborhood: "San Pedro Square",
//     city: "San Jose",
//     time: "20 min",
//     image: pic1,
//   },
//   {
//     id: 2,
//     type: "coffee",
//     name: "Big Mug Coffee",
//     neighborhood: "El Camino Business District",
//     city: "Santa Clara",
//     time: "15 min",
//     image: pic1,
//   },

//   {
//     id: 3,
//     type: "view",
//     name: "Vasona Park",
//     neighborhood: "Los Gatos Creek Trail",
//     city: "Los Gatos",
//     image: pic1,
//   },
//   {
//     id: 4,
//     type: "coffee",
//     name: "Blue Bottle Coffee",
//     city: "San Jose",
//     time: "15 min",
//     image: pic1,
//   },
//   {
//     id: 5,
//     name: "Tower Hall",
//     neighborhood: "San Jose State",
//     city: "San Jose",
//     time: "5 min",
//     image: pic1,
//   },
//   {
//     type: "view",
//     name: "Baylands Park",
//     neighborhood: "Alviso",
//     city: "San Jose",
//     time: "20 min",
//     image: pic1,
//   },
//   {
//     id: 7,
//     type: "view",
//     name: "Baylands Park",
//     neighborhood: "Alviso",
//     city: "San Jose",
//     time: "20 min",
//     image: pic1,
//   },
//   {
//     id: 8,
//     type: "landmark",
//     name: "Campbell Water Tower",
//     neighborhood: "Downtown Campbell",
//     city: "Campbell",
//     time: "5 min",
//     image: pic1,
//   },
//   {
//     id: 9,
//     type: "landmark",
//     name: "Don Burnette Bridge",
//     neighborhood: "De Anza College",
//     city: "Cupertino",
//     time: "18 min",
//     image: pic1,
//   },
// ];
