// import pic1 from "./sjsu.png";

const seedData = [
  {
    name: "Blue Bottle",
    category: "coffee",
    neighborhood: "Santana Row",
    rating: 4.9,
    distanceMiles: 5,
    attributes: [
      "Locally Owned",
      "Mtn Bike Recommended",
      "Quality Coffee",
      "️️Bike Parking",
      "Bottle Refill",
      "Bathrooms",
      "Outdoor Seating",
    ],
    loc: {
      type: "Point",
      coordinates: [-121.9478553, 37.3202302],
    },
  },
  {
    name: "Papermoon Cafe",
    category: "coffee",
    neighborhood: "Santana Row",
    rating: 3.5,
    distanceMiles: 6,
    attributes: [
      "Locally Owned",
      "Mtn Bike Recommended",
      "Quality Coffee",
      "️️Bike Parking",
      "Bottle Refill",
      "Bathrooms",
      "Outdoor Seating",
    ],
    loc: {
      type: "Point",
      coordinates: [-121.9944611, 37.3239944],
    },
  },
  {
    name: "Voyager Craft Coffee",
    category: "coffee",
    neighborhood: "Downtown Santa Clara",
    rating: 4.5,
    distanceMiles: 7,
    attributes: [
      "Locally Owned",
      "Mtn Bike Recommended",
      "Quality Coffee",
      "️️Bike Parking",
      "Bottle Refill",
      "Bathrooms",
      "Outdoor Seating",
    ],
    loc: { type: "Point", coordinates: [-121.972528, 37.32362] },
  },
  {
    name: "Sue's Gallery Cafe",
    category: "coffee",
    neighborhood: "Downtown Saratoga",
    rating: 5,
    distanceMiles: 4,
    attributes: [
      "Locally Owned",
      "Mtn Bike Recommended",
      "Quality Coffee",
      "️️Bike Parking",
      "Bottle Refill",
      "Bathrooms",
      "Outdoor Seating",
    ],
    loc: { type: "Point", coordinates: [-122.0374028, 37.2558028] },
  },
  {
    name: "Vasona Lake",
    category: "view",
    neighborhood: "Los Gatos Creek",
    rating: 4.5,
    distanceMiles: 3,
    attributes: [
      "Locally Owned",
      "Mtn Bike Recommended",
      "Quality Coffee",
      "️️Bike Parking",
      "Bottle Refill",
      "Bathrooms",
      "Outdoor Seating",
    ],
    loc: { type: "Point", coordinates: [-121.9725622, 37.2348826] },
  },

  {
    name: "Communication Hills",
    category: "view",
    neighborhood: "South San Jose",
    rating: 5,
    distanceMiles: 8,
    attributes: [
      "Locally Owned",
      "Mtn Bike Recommended",
      "Quality Coffee",
      "️️Bike Parking",
      "Bottle Refill",
      "Bathrooms",
      "Outdoor Seating",
    ],
    loc: { type: "Point", coordinates: [-121.8598135, 37.2848984] },
  },
  {
    name: "Baylands Park",
    category: "view",
    neighborhood: "North San Jose",
    rating: 4.9,
    distanceMiles: 5,
    attributes: [
      "Locally Owned",
      "Mtn Bike Recommended",
      "Quality Coffee",
      "️️Bike Parking",
      "Bottle Refill",
      "Bathrooms",
      "Outdoor Seating",
    ],
    loc: { type: "Point", coordinates: [-121.9979576, 37.4124569] },
  },
  {
    name: "Campbell Perc Ponds",
    category: "view",
    neighborhood: "Los Gatos Creek",
    rating: 4.5,
    distanceMiles: 3,
    attributes: [
      "Locally Owned",
      "Mtn Bike Recommended",
      "Quality Coffee",
      "️️Bike Parking",
      "Bottle Refill",
      "Bathrooms",
      "Outdoor Seating",
    ],
    loc: { type: "Point", coordinates: [-121.9506961, 37.2687858] },
  },

  {
    name: "SJSU Tower Hall",
    category: "landmark",
    neighborhood: "San Jose State University",
    rating: 4.9,
    distanceMiles: 5,
    attributes: [
      "Locally Owned",
      "Mtn Bike Recommended",
      "Quality Coffee",
      "️️Bike Parking",
      "Bottle Refill",
      "Bathrooms",
      "Outdoor Seating",
    ],
    loc: { type: "Point", coordinates: [-121.8834692, 37.3352937] },
  },
  {
    name: "Mission Santa Clara",
    category: "landmark",
    neighborhood: "Santa Clara University",
    rating: 4,
    distanceMiles: 6,
    attributes: [
      "Locally Owned",
      "Mtn Bike Recommended",
      "Quality Coffee",
      "️️Bike Parking",
      "Bottle Refill",
      "Bathrooms",
      "Outdoor Seating",
    ],
    loc: { type: "Point", coordinates: [-121.941533, 37.3492149] },
  },
  {
    name: "Farm Milk Dairy",
    category: "landmark",
    neighborhood: "HazelWood",
    rating: 5,
    distanceMiles: 0.1,
    attributes: [
      "Locally Owned",
      "Mtn Bike Recommended",
      "Quality Coffee",
      "️️Bike Parking",
      "Bottle Refill",
      "Bathrooms",
      "Outdoor Seating",
    ],
    loc: { type: "Point", coordinates: [-121.9712076, 37.2739255] },
  },
  {
    name: "Campbell Water Tower",
    category: "landmark",
    neighborhood: "Downtown Campbell",
    rating: 4.9,
    distanceMiles: 5,
    attributes: [
      "Locally Owned",
      "Mtn Bike Recommended",
      "Quality Coffee",
      "️️Bike Parking",
      "Bottle Refill",
      "Bathrooms",
      "Outdoor Seating",
    ],
    loc: { type: "Point", coordinates: [-121.9445335, 37.28584499999999] },
  },
  {
    name: "AndyTown",
    category: "coffee",
    neighborhood: "Sunset District",
    rating: 4.9,
    distanceMiles: 5,
    attributes: [
      "Locally Owned",
      "Quality Coffee",
      "️️Bike Parking",
      "Bottle Refill",
      "Outdoor Seating",
    ],
    loc: { type: "Point", coordinates: [-122.5023147, 37.7566712] },
  },
  {
    name: "Devout Coffee",
    category: "coffee",
    neighborhood: "Niles Fremont",
    rating: 4.9,
    distanceMiles: 5,
    attributes: [
      "Locally Owned",
      "Quality Coffee",
      "️️Bike Parking",
      "Bottle Refill",
      "Outdoor Seating",
    ],
    loc: { type: "Point", coordinates: [-121.9807223, 37.577231] },
  },
];
module.exports = seedData;
