// import pic1 from "./sjsu.png";

const seedData = [
  {
    name: "Blue Bottle",
    category: "coffee",
    neighborhood: "Santana Row",
    rating: 4.9,
    distanceMiles: 5,
    attributes: [
      "Locally Owned",
      "Mtn Bike Recommended",
      "Quality Coffee",
      "️️Bike Parking",
      "Bottle Refill",
      "Bathrooms",
      "Outdoor Seating",
    ],
  },
  {
    name: "Papermoon Cafe",
    category: "coffee",
    neighborhood: "Santana Row",
    rating: 3.5,
    distanceMiles: 6,
    attributes: [
      "Locally Owned",
      "Mtn Bike Recommended",
      "Quality Coffee",
      "️️Bike Parking",
      "Bottle Refill",
      "Bathrooms",
      "Outdoor Seating",
    ],
  },
  {
    name: "Voyager Craft Coffee",
    category: "coffee",
    neighborhood: "Downtown Santa Clara",
    rating: 4.5,
    distanceMiles: 7,
    attributes: [
      "Locally Owned",
      "Mtn Bike Recommended",
      "Quality Coffee",
      "️️Bike Parking",
      "Bottle Refill",
      "Bathrooms",
      "Outdoor Seating",
    ],
  },
  {
    name: "Sue's Gallery Cafe",
    category: "coffee",
    neighborhood: "Downtown Saratoga",
    rating: 5,
    distanceMiles: 4,
    attributes: [
      "Locally Owned",
      "Mtn Bike Recommended",
      "Quality Coffee",
      "️️Bike Parking",
      "Bottle Refill",
      "Bathrooms",
      "Outdoor Seating",
    ],
  },
  {
    name: "Vasona Lake",
    category: "view",
    neighborhood: "Los Gatos Creek",
    rating: 4.5,
    distanceMiles: 3,
    attributes: [
      "Locally Owned",
      "Mtn Bike Recommended",
      "Quality Coffee",
      "️️Bike Parking",
      "Bottle Refill",
      "Bathrooms",
      "Outdoor Seating",
    ],
  },

  {
    name: "Communication Hills",
    category: "view",
    neighborhood: "South San Jose",
    rating: 5,
    distanceMiles: 8,
    attributes: [
      "Locally Owned",
      "Mtn Bike Recommended",
      "Quality Coffee",
      "️️Bike Parking",
      "Bottle Refill",
      "Bathrooms",
      "Outdoor Seating",
    ],
  },
  {
    name: "Baylands Park",
    category: "view",
    neighborhood: "North San Jose",
    rating: 4.9,
    distanceMiles: 5,
    attributes: [
      "Locally Owned",
      "Mtn Bike Recommended",
      "Quality Coffee",
      "️️Bike Parking",
      "Bottle Refill",
      "Bathrooms",
      "Outdoor Seating",
    ],
  },
  {
    name: "Campbell Perc Ponds",
    category: "view",
    neighborhood: "Los Gatos Creek",
    rating: 4.5,
    distanceMiles: 3,
    attributes: [
      "Locally Owned",
      "Mtn Bike Recommended",
      "Quality Coffee",
      "️️Bike Parking",
      "Bottle Refill",
      "Bathrooms",
      "Outdoor Seating",
    ],
  },

  {
    name: "SJSU Tower Hall",
    category: "landmark",
    neighborhood: "San Jose State University",
    rating: 4.9,
    distanceMiles: 5,
    attributes: [
      "Locally Owned",
      "Mtn Bike Recommended",
      "Quality Coffee",
      "️️Bike Parking",
      "Bottle Refill",
      "Bathrooms",
      "Outdoor Seating",
    ],
  },
  {
    name: "Mission Santa Clara",
    category: "landmark",
    neighborhood: "Santa Clara University",
    rating: 4,
    distanceMiles: 6,
    attributes: [
      "Locally Owned",
      "Mtn Bike Recommended",
      "Quality Coffee",
      "️️Bike Parking",
      "Bottle Refill",
      "Bathrooms",
      "Outdoor Seating",
    ],
  },
  {
    name: "Farm Milk Dairy",
    category: "landmark",
    neighborhood: "HazelWood",
    rating: 5,
    distanceMiles: 0.1,
    attributes: [
      "Locally Owned",
      "Mtn Bike Recommended",
      "Quality Coffee",
      "️️Bike Parking",
      "Bottle Refill",
      "Bathrooms",
      "Outdoor Seating",
    ],
  },
  {
    name: "Campbell Water Tower",
    category: "landmark",
    neighborhood: "Downtown Campbell",
    rating: 4.9,
    distanceMiles: 5,
    attributes: [
      "Locally Owned",
      "Mtn Bike Recommended",
      "Quality Coffee",
      "️️Bike Parking",
      "Bottle Refill",
      "Bathrooms",
      "Outdoor Seating",
    ],
  },
];
module.exports = seedData;
